### ISSUE TITLE
Downloading fails.

### ISSUE THREAD

**Issue by TTN-** [liamdiprose/LearnPDF#9]
```Traceback (most recent call last):
  File "./main.py", line 143, in <module>
    main(args)
  File "./main.py", line 98, in main
    download(file['url'], filepath)
  File "./main.py", line 56, in download
    urllib.request.urlretrieve(src, dst)
  File "C:\Python34\lib\urllib\request.py", line 196, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'learn\\COSC262-18S1\\Quizzes and assignments \\AssignmentII_2018.pdf'

C:\Users\User\Desktop\learnScrape\LearnPDF>
```

A file path error? `learn\\` doesn't look like a valid path to me thats for sure.

Restarted the downloading fresh, without resuming, still fails with the same issue.

**Comment by liamdiprose** [comment]
This is probably a problem with the difference between how Windows and Linux handle file paths. 

I've only tested LearnPDF on my Linux install, which is why you're having trouble. However, seeing that we have Windows users now, I'm quite happy to start testing on Windows too.

I'm installing a VM now, so I'll hopefully get back to you with a fix :+1:

**Comment by TTN-** [comment]
Alternatively.. Linux subsystem on Windows 10 could be an alternative perhaps.

**Comment by liamdiprose** [comment]
I don't know anything about Windows, or the Linux subsystem, so I cant say if that will work or not.

I've just successfully run learnpdf on windows, which I wasn't expecting. I've rechecked your error, and the path contains an unescaped space at the end of "Quizzes and Assignments ".
This is surely a lecturer mistake, but we should be able to deal with it.

I'll edit the code that creates the filepath to strip tailing spaces from each part.

**Comment by liamdiprose** [comment]
Alright, that _should_ work. Let me know how it goes :crossed_fingers:

**Comment by TTN-** [comment]
Thanks.

```
line 24, in get_token
    raise PermissionError(r['error'])
PermissionError: The site is undergoing maintenance and is currently not available
```
I sure hope the content is there after they are done!! Will let you know how it goes once its back online.

**Comment by TTN-** [comment]
Perfect. Fixed and thank you very much!
